### ISSUE TITLE
When will 1.1.0 final be released?

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-dotnet-extensions#50] opened 2020-09-10 14:44 UTC
Really looking forward to being able to use the [new features](https://github.com/Azure/azure-functions-dotnet-extensions/wiki/Configuration-and-FunctionsHostBuilderContext-support) - how long is it necessary to keep these in preview, considering that the requisite runtime versions have long been rolled out to all Azure customers?

**Comment by jackbond** [comment] 2020-09-11 20:07
Also waiting for non-preview release. :)

**Comment by anthonychu** [comment] 2020-09-15 06:45
Synced with @brettsam and @fabiocav today. Should be published soon!

**Comment by fabiocav** [comment] 2020-09-15 17:56
Assigning this to sprint 84 as a stretch goal. Sprint 84 ends tomorrow, so it's possible this will slip into the beginning of sprint 85.

**Comment by jackbond** [comment] 2020-09-15 18:20
How long are your sprints? :)

**Comment by fabiocav** [comment] 2020-09-15 23:54
Functions sprints are 2 weeks long. That will map to the milestone the issue is assigned to and each milestone has a due date set.

**Comment by brettsam** [comment] 2020-09-16 14:54
I've just published it: https://www.nuget.org/packages/Microsoft.Azure.Functions.Extensions/1.1.0

**Closed by brettsam** 2020-09-16 14:54 UTC

**Comment by jackbond** [comment] 2020-09-16 14:55
Awesome! Thanks.

**Comment by IanKemp** [comment] 2020-09-16 14:59
yesssss
